### PR TITLE
Fix ExcelProvider

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #318

### CODE REVIEW

**Comment by paulverdu** [comment]
This fixes the problem with the processor callback function.
Only problem now that when the processor returns null, in case of the first 'headers row'. The first iteration of $dataset in Importer:runImport() runs importRow() with variable $row being null.

The parameter $data in importRow() is not nullable at the moment. This exception is catched, but is not ideal.
Making $data nullable will make $object in Importer null but this will count as 1 row being processed which is also not ideal. There for I think we should do a continue in Importer:runImport() just before the try catch:

```
if ($row === null) {
    continue;
}
```

This will not make the first $row being null count as a row being processed.

What do you think @dpfaffenbauer ?

**Comment by dpfaffenbauer** [comment]
I would actually have to test that use-case myself. I'll comeback to you with a solution

**Comment by paulverdu** [comment]
Screen Shot 2021-08-16 at 13 38 06

So this would be my solution for this problem.

**Comment by paulverdu** [comment]
> I would actually have to test that use-case myself. I'll comeback to you with a solution

Ok, thanks

**Comment by paulverdu** [comment]
```
if (null === $data) {
    return null;
}
```

This code in Importer:importRow() can be removed then as well since parameter $data is not nullable, so this code already never gets executed atm.

**Comment by dpfaffenbauer** [comment]
@paulverdu Did the changes you recommended. Seems that in fact you are right here :)

**Comment by paulverdu** [comment]
> @paulverdu Did the changes you recommended. Seems that in fact you are right here :)

Awesome. Hope we can merge this soon, so we can continue testing our application 😄

**Comment by dpfaffenbauer** [comment]
done :)

**Pull request merged**
