### PR TITLE
 Fixes on the current version.

### PR DESCRIPTION
**Pull request by tip-top-b**
- Returning the id to the function, to prevent overwriting definitions with the same name.
- Adding commands for converting the old structure to the new structure, and systems that have to be upgraded.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes/no
| Fixed tickets | #...

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@tip-top-b This adds a new ID int field to the definitions?

**Comment by dpfaffenbauer** [comment]
@tip-top-b I see why you added that again, and it makes total sense! I made some further adjustments and refactorings. It didn't quite well work in all scenarios, for example if configured as settings-store.

**Comment by tip-top-b** [comment]
@dpfaffenbauer thanks a lot.

**Comment by dpfaffenbauer** [comment]
@tip-top-b thank you ;)

I will do a release tomorrow. will be 5.1. major bc break though, but necessary

**Pull request merged**
