### PR TITLE
Add missing type casting interpreter definition

### PR DESCRIPTION
**Pull request by bramstroker**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no

TypeCastingInterpreter was missing from services.yml.

### CODE REVIEW

**Comment by bramstroker** [comment]
Changed to draft. Also need to add configuration form still I see to allow user to choose the type to cast to.

I need this interpreter in our project because of the strict typing which has been added to Pimcore 11 class getters and setters.

Currently I'm using the map interpreter and objectbrick setter.
But the map interpreter returns a string and the setter expects an integer. So the solution I'm implementing now is to use the nested interpreter with map and type_casting.

Might be a cleaner solution to let the objectbrick setter detect the fieldType automatically and do the correct type casting accordingly when needed. Thoughts?

**Comment by bramstroker** [comment]
This is working now on my installation now. Had some object fields in some imports which expected a `float` or `int` type. But all values extracted from the CSV are strings obviously. This will cause fatal errors in PHP due to strict type hints on the object setters. 
Adding the type casting interpreter for these cases solved my problem.

**Comment by bramstroker** [comment]
@dpfaffenbauer Sorry for pinging, but any chance this can be merged on short term?

**Comment by dpfaffenbauer** [comment]
@bramstroker thanks for pinging, I somehow missed it.

**Review by dpfaffenbauer — APPROVED** [review]

**Comment by dpfaffenbauer** [comment]
thanks for the contribution

**Comment by bramstroker** [comment]
Thanks!

**Pull request merged**
