### PR TITLE
Added note-in-version while products imported

### PR DESCRIPTION
**Pull request by tjgumis**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | yes/no
| Fixed tickets | #...

### CODE REVIEW

**Comment by tjgumis** [comment]
Recently, our attention was drawn to the usefulness of information about the way in which the product / asset was added. From a practical point of view, we need at least some markers in relation to imported items.

**Comment by dpfaffenbauer** [comment]
I understand the idea, but this is to generic. Not everybody wants the notes to blow up cause of this change. We should rather introduce a new feature that allows that.

**Comment by tjgumis** [comment]
Thanks for an immediate reaction. What about adding an option to the import configuration?

**Comment by dpfaffenbauer** [comment]
or mabye some kind of service to programmatically define what note to store per object

**Comment by aarongerig** [comment]
I would go for a programmatic approach as well, as it is much more flexible than configuration.

**Comment by tjgumis** [comment]
Gentlemen, it looks like you've already got some thoughtful reflection on that matter. The service idea looks indeed promising, but I wonder if you have some more specific perspective/idea (code flow schema) and of course if you don't mind sharing it. Simply saying, how would you do it?

**Comment by dpfaffenbauer** [comment]
Similar to a Data Provider or Runner: Introduce a Data Object Persisting Service that handles the save. The default "persister" is just a save call. If you have more "complex" use-cases, create your own persister that adds a note as well.

**Comment by tjgumis** [comment]
Thank you.

**Comment by tjgumis** [comment]
I did my best to follow all suggestions, so if you can review the code ...

**Comment by dpfaffenbauer** [comment]
Seems legit to me. @aarongerig ?

**Review by dpfaffenbauer — APPROVED** [review]

**Comment by aarongerig** [comment]
LGTM as well.

**Review by aarongerig — APPROVED** [review]

**Comment by tjgumis** [comment]
Thank you gentlemen.

**Comment by dpfaffenbauer** [comment]
thanks a lot

**Pull request merged**
