### PR TITLE
Add configurable date format to Carbon interpreter

### PR DESCRIPTION
**Pull request by bramstroker**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no

Add possibility to define a custom date format in the Carbon interpreter, so we can use arbitrary dates while importing.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
I am thinking about if I should merge that now, and have to refactor it later to suite #199, or if I merge #199 first and you have to change this PR according to it.

#199 is a huge refactor which changes the name of the Bundle and adds a BC Layer for the old class-names

**Comment by bramstroker** [comment]
@dpfaffenbauer Not in a hurry to get this merged to master. I can retarget this PR to your refactor branch than you can merge it and make the changes for the namespacing, would that be an idea?

**Comment by dpfaffenbauer** [comment]
If you're not in a hurry, let's wait for #199 to be merged. Hope I can get it done till end of this week anyway

**Comment by bramstroker** [comment]
Ok that's fine dominic. But I need to make changes than to match the new namespacing, or can you do that when this is about to get merged?

**Comment by dpfaffenbauer** [comment]
would be good if you could do it

**Comment by dpfaffenbauer** [comment]
#199 is merged, can you adapt your PR now pls?

**Comment by bramstroker** [comment]
Will have a look at it next tuesday

**Comment by dpfaffenbauer** [comment]
and please base it agains the 2.3 branch, I'll merge it up to master once its done.

Thanks

**Comment by bramstroker** [comment]
New PR based on 2.3

**Pull request closed without merging**
